### ISSUE TITLE
Upload .zip file size limit

### ISSUE THREAD

**Issue by Naigege** [SEL-Columbia/modelrunner#21]
One .zip file (25.9 MB) was failed to be uploaded. So there may be file size limit in Modelrunner.io 

One temporary solution is deleting dataset.db and re-zip in windows system.

**Comment by chrisnatali** [comment]
Marking this as closed since I updated the nginx config to allow files up to 50 MB and I see input.zip's that have been uploaded that are upwards of 100 MB.
